package com.frees.backend.core;

import com.frees.backend.core.ode.OdeTableResult;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Method-of-lines: a 1-D transient heat-conduction rod discretized into N nodes,
 * with der(T[i]) generated by a FOR loop and a vector initial condition
 * T[2:N-1](0). Reuses the array / FOR expansion machinery so each node becomes
 * a scalar state t[i]. Validates against the steady-state linear profile.
 */
class DynamicArrayStatesTest {

    private final EquationSystemSolver solver = new EquationSystemSolver();

    private double col(OdeTableResult t, String name) {
        int ci = t.columns().indexOf(name);
        List<Double> last = t.rows().get(t.rows().size() - 1);
        return last.get(ci);
    }

    @Test
    void transientHeatRodReachesLinearSteadyState() {
        // 6 nodes, boundaries held at 100 and 0, interior starts cold. After long
        // enough the interior approaches the linear steady profile 80/60/40/20.
        String src = """
                N = 6
                L = 1
                dx = L / (N - 1)
                alpha = 0.05
                T_left = 100
                T_right = 0
                T_init = 0
                DYNAMIC rod (method = ode23s, t = 0 .. 300, points = 120, rtol = 1e-6)
                  FOR i = 2 TO N-1
                    der(T[i]) = alpha / dx^2 * (T[i-1] - 2*T[i] + T[i+1])
                  END
                  T[1] = T_left
                  T[6] = T_right
                  T[2:N-1](0) = T_init
                END
                """;
        var result = solver.solve(src);
        assertEquals(1, result.odeTables().size());
        OdeTableResult tbl = result.odeTables().get(0);
        // Columns include each interior state and the boundary auxiliaries.
        assertTrue(tbl.columns().containsAll(List.of("t", "t[2]", "t[3]", "t[4]", "t[5]")),
                tbl.columns().toString());

        // Steady linear profile: T[i] = 100 (N-i)/(N-1).
        assertEquals(80.0, col(tbl, "t[2]"), 2.0);
        assertEquals(60.0, col(tbl, "t[3]"), 2.0);
        assertEquals(40.0, col(tbl, "t[4]"), 2.0);
        assertEquals(20.0, col(tbl, "t[5]"), 2.0);
    }

    @Test
    void rodWithOde45Also() {
        // The same discretization with the default adaptive method.
        String src = """
                N = 5
                dx = 0.25
                alpha = 0.05
                DYNAMIC rod (method = ode45, t = 0 .. 400, points = 100, rtol = 1e-7)
                  FOR i = 2 TO N-1
                    der(T[i]) = alpha / dx^2 * (T[i-1] - 2*T[i] + T[i+1])
                  END
                  T[1] = 100
                  T[5] = 0
                  T[2:4](0) = 0
                END
                """;
        OdeTableResult tbl = solver.solve(src).odeTables().get(0);
        // Steady: T[2]=75, T[3]=50, T[4]=25.
        assertEquals(75.0, col(tbl, "t[2]"), 2.0);
        assertEquals(50.0, col(tbl, "t[3]"), 2.0);
        assertEquals(25.0, col(tbl, "t[4]"), 2.0);
    }
}
