#!/bin/sh
# frees installer — https://github.com/ernsoylu/frees
#
#   curl -fsSL https://raw.githubusercontent.com/ernsoylu/frees/main/install.sh | sh
#
# Downloads one compose file and starts the published images. Installs nothing
# outside its own directory, needs no root, and touches no system paths — undo
# it with `frees stop` and `rm -rf ~/.frees`.
#
# POSIX sh on purpose: the documented entry point pipes into `sh`, so bashisms
# ([[ ]], arrays, local) would break on a dash/ash /bin/sh.
#
# Everything is wrapped in main() and called on the LAST line, so a connection
# that drops mid-download can't leave a half-script that executes a truncated
# command. Do not move that call or add top-level statements after it.

set -eu

REPO_RAW="https://raw.githubusercontent.com/ernsoylu/frees/main"
FREES_HOME="${FREES_HOME:-$HOME/.frees}"
COMPOSE_FILE="docker-compose.local.yml"
FREES_VERSION="${FREES_VERSION:-latest}"

# Colour only when stdout is a terminal — piped into a log this must stay plain.
if [ -t 1 ]; then
    B="$(printf '\033[1m')"; DIM="$(printf '\033[2m')"
    RED="$(printf '\033[31m')"; GRN="$(printf '\033[32m')"; YEL="$(printf '\033[33m')"
    RST="$(printf '\033[0m')"
else
    B=''; DIM=''; RED=''; GRN=''; YEL=''; RST=''
fi

say()  { printf '%s\n' "$*"; }
step() { printf '%s==>%s %s\n' "$B" "$RST" "$*"; }
warn() { printf '%s warning:%s %s\n' "$YEL" "$RST" "$*" >&2; }
die()  { printf '%serror:%s %s\n' "$RED" "$RST" "$*" >&2; exit 1; }

have() { command -v "$1" >/dev/null 2>&1; }

check_prereqs() {
    have docker || die "docker is not installed. See https://docs.docker.com/get-docker/"

    # `docker info` is the honest check: the CLI exists on plenty of machines
    # where the daemon/VM isn't running, and every later command would fail
    # with a much less obvious error.
    if ! docker info >/dev/null 2>&1; then
        die "the Docker daemon isn't reachable. Start Docker Desktop / Rancher Desktop / the docker service, then re-run."
    fi

    # Compose v2 is a docker subcommand. v1 (`docker-compose`) is EOL and does
    # not understand `depends_on: condition: service_healthy` the way this
    # compose file relies on, so refuse rather than half-work.
    if ! docker compose version >/dev/null 2>&1; then
        die "Docker Compose v2 is required (the 'docker compose' subcommand). Your Docker install only has the legacy 'docker-compose' binary."
    fi
}

fetch() {
    # $1 = url, $2 = destination
    if have curl; then
        curl -fsSL "$1" -o "$2"
    elif have wget; then
        wget -qO "$2" "$1"
    else
        die "neither curl nor wget is available to download $1"
    fi
}

install_compose_file() {
    mkdir -p "$FREES_HOME"
    step "Fetching $COMPOSE_FILE into $FREES_HOME"
    # Download beside the target and move into place, so an interrupted fetch
    # leaves the previous working file intact rather than a truncated one.
    fetch "$REPO_RAW/$COMPOSE_FILE" "$FREES_HOME/$COMPOSE_FILE.tmp"
    mv "$FREES_HOME/$COMPOSE_FILE.tmp" "$FREES_HOME/$COMPOSE_FILE"
}

start_stack() {
    step "Pulling images (frees:$FREES_VERSION) — first run downloads ~3 GB"
    ( cd "$FREES_HOME" && FREES_VERSION="$FREES_VERSION" docker compose -f "$COMPOSE_FILE" pull -q )

    step "Starting frees"
    ( cd "$FREES_HOME" && FREES_VERSION="$FREES_VERSION" docker compose -f "$COMPOSE_FILE" up -d )
}

wait_for_ready() {
    step "Waiting for the stack to come up"
    i=0
    while [ "$i" -lt 90 ]; do
        if have curl && curl -fsS -o /dev/null http://127.0.0.1:5173/ 2>/dev/null; then
            return 0
        fi
        i=$((i + 1))
        sleep 2
    done
    # Not fatal: the images are pulled and the containers are up, so pointing
    # the user at logs beats failing an install that probably just needs longer
    # on a slow machine.
    warn "frees did not answer on http://localhost:5173 within 3 minutes."
    warn "Check progress with:  cd $FREES_HOME && docker compose -f $COMPOSE_FILE logs -f"
    return 0
}

install_launcher() {
    # A tiny wrapper so users get `frees start|stop|...` without needing to
    # remember the compose invocation or the install directory.
    launcher="$FREES_HOME/frees"
    cat > "$launcher" <<EOF
#!/bin/sh
# frees launcher — generated by install.sh
set -eu
cd "\$(dirname "\$0")"
export FREES_VERSION="\${FREES_VERSION:-$FREES_VERSION}"
case "\${1:-}" in
    start)   docker compose -f $COMPOSE_FILE up -d ;;
    stop)    docker compose -f $COMPOSE_FILE down ;;
    restart) docker compose -f $COMPOSE_FILE down && docker compose -f $COMPOSE_FILE up -d ;;
    status)  docker compose -f $COMPOSE_FILE ps ;;
    logs)    docker compose -f $COMPOSE_FILE logs -f ;;
    update)  docker compose -f $COMPOSE_FILE pull && docker compose -f $COMPOSE_FILE up -d ;;
    *) echo "Usage: frees {start|stop|restart|status|logs|update}" >&2; exit 1 ;;
esac
EOF
    chmod +x "$launcher"
}

print_done() {
    say ""
    printf '%sfrees is running:%s http://localhost:5173\n' "$GRN" "$RST"
    say ""
    say "  ${B}$FREES_HOME/frees${RST} start | stop | restart | status | logs | update"
    say ""
    say "${DIM}Add it to your PATH for convenience:${RST}"
    say "  export PATH=\"\$PATH:$FREES_HOME\""
    say ""
    say "${DIM}Pin a specific build (any tag CI publishes, e.g. a commit sha):${RST}"
    say "  FREES_VERSION=<sha> $FREES_HOME/frees update"
    say ""
    say "${DIM}Uninstall: $FREES_HOME/frees stop && rm -rf $FREES_HOME${RST}"
}

main() {
    say ""
    say "${B}frees${RST} — declarative equation solving for engineering problems"
    say ""
    check_prereqs
    install_compose_file
    start_stack
    install_launcher
    wait_for_ready
    print_done
}

main "$@"
