package com.frees.backend.ast;

import org.apache.commons.math3.linear.Array2DRowRealMatrix;
import org.apache.commons.math3.linear.EigenDecomposition;
import org.apache.commons.math3.linear.RealVector;

import java.util.Comparator;
import java.util.List;
import java.util.Map;

/** Evaluates an expression AST against current variable values. */
public final class Evaluator {

    private Evaluator() {}

    public static double eval(Expr e, Map<String, Double> values) {
        return eval(e, values, Map.of());
    }

    public static double eval(Expr e, Map<String, Double> values, Map<String, ProcDef> defs) {
        return switch (e) {
            case Expr.Num(double value, String unit, boolean isImaginary) -> value;
            case Expr.Str(String value) -> throw new IllegalStateException(
                    "String literal '" + value + "' cannot be evaluated as a number. "
                    + "String literals are only valid in function arguments like property calls.");
            case Expr.Var(String name) -> {
                Double value = values.get(name);
                if (value == null) {
                    throw new IllegalStateException("Variable has no value: " + name);
                }
                yield value;
            }
            case Expr.Neg(Expr operand) -> -eval(operand, values, defs);
            case Expr.BinOp(char op, Expr left, Expr right) -> {
                double l = eval(left, values, defs);
                double r = eval(right, values, defs);
                yield switch (op) {
                    case '+' -> l + r;
                    case '-' -> l - r;
                    case '*' -> l * r;
                    case '/' -> l / r;
                    case '^' -> Math.pow(l, r);
                    default -> throw new IllegalStateException("Unknown operator: " + op);
                };
            }
            case Expr.Call(String function, List<Expr> args) -> evalCall(new Expr.Call(function, args), values, defs);
            case Expr.ArrayAccess(String name, List<Expr> indices) -> throw new IllegalStateException("ArrayAccess cannot be evaluated directly: " + name);
            case Expr.Range(Expr start, Expr end) -> throw new IllegalStateException("Range cannot be evaluated directly: " + start + ".." + end);
            case Expr.ArrayLiteral(List<Expr> elements) -> throw new IllegalStateException("ArrayLiteral cannot be evaluated directly: " + elements);
            case Expr.Compare(String op, Expr left, Expr right) -> {
                double l = eval(left, values, defs);
                double r = eval(right, values, defs);
                boolean result = switch (op) {
                    case "<"  -> l < r;
                    case ">"  -> l > r;
                    case "<=" -> l <= r;
                    case ">=" -> l >= r;
                    case "<>" -> l != r;
                    case "="  -> l == r;
                    default -> throw new IllegalStateException("Unknown comparison operator: " + op);
                };
                yield result ? 1.0 : 0.0;
            }
            case Expr.Logical(String op, Expr left, Expr right) -> {
                double l = eval(left, values, defs);
                double r = eval(right, values, defs);
                boolean result = switch (op) {
                    case "and" -> l != 0.0 && r != 0.0;
                    case "or"  -> l != 0.0 || r != 0.0;
                    default -> throw new IllegalStateException("Unknown logical operator: " + op);
                };
                yield result ? 1.0 : 0.0;
            }
            case Expr.Not(Expr operand) -> eval(operand, values, defs) == 0.0 ? 1.0 : 0.0;
        };
    }

    private static double evalCall(Expr.Call c, Map<String, Double> values, Map<String, ProcDef> defs) {
        ProcDef def = defs.get(c.function());

        // Tabulated Function Table function: name(x) or name(x, param)
        if (def instanceof ProcDef.FunctionTableDef cd) {
            if (c.args().isEmpty() || c.args().size() > 2) {
                throw new IllegalStateException("Function table '" + cd.name()
                        + "' expects " + cd.name() + "(x) or " + cd.name() + "(x, param).");
            }
            double x = eval(c.args().get(0), values, defs);
            Double param = c.args().size() == 2 ? eval(c.args().get(1), values, defs) : null;
            return com.frees.backend.core.CurveInterpolator.evaluate(cd, x, param);
        }

        // Dispatch to user-defined FUNCTION
        if (def instanceof ProcDef.FunctionDef fd) {
            List<Double> args = c.args().stream()
                    .map(a -> eval(a, values, defs))
                    .toList();
            return new com.frees.backend.parser.ProcedureEvaluator(defs).callFunction(fd, args, values);
        }

        // Fluid property call: prop$<output>$<fluid>$<ind1>$<ind2>(values...)
        // Generated by AstBuilder from e.g. Enthalpy(R134a, T=T1, x=1).
        if (c.function().startsWith(com.frees.backend.props.PropertyFunctions.PREFIX)) {
            List<Double> propArgs = c.args().stream()
                    .map(a -> eval(a, values, defs))
                    .toList();
            return com.frees.backend.props.PropertyFunctions.evaluate(c.function(), propArgs);
        }

        // Synthetic procedure output call: proc$<name>$<outputIndex>(inputs...)
        // Generated by EquationParser when flattening CALL statements.
        if (c.function().startsWith("proc$")) {
            String[] parts = c.function().split("\\$", 3);
            if (parts.length == 3) {
                String procName = parts[1];
                int outputIndex = Integer.parseInt(parts[2]);
                ProcDef procDef = defs.get(procName);
                if (procDef instanceof ProcDef.ProcedureDef pd) {
                    List<Double> inputVals = c.args().stream()
                            .map(a -> eval(a, values, defs))
                            .toList();
                    Map<String, Double> outputs =
                            new com.frees.backend.parser.ProcedureEvaluator(defs)
                                    .callProcedure(pd, inputVals, values);
                    String outKey = pd.outputs().get(outputIndex).toLowerCase();
                    return outputs.get(outKey);
                }
            }
        }

        // Synthetic eigendecomposition call: eigen$val$<k>$<n> or eigen$vec$<i>$<k>$<n>,
        // with the n*n matrix entries (row-major) as arguments.
        // Generated by EquationParser when flattening CALL Eigenvalues / CALL Eigen.
        if (c.function().startsWith("eigen$")) {
            return evalEigen(c, values, defs);
        }

        // Built-in functions
        List<Expr> args = c.args();
        return switch (c.function()) {
            case "abs"    -> Math.abs(arg(c, args, 0, values, defs));
            case "exp"    -> Math.exp(arg(c, args, 0, values, defs));
            case "ln"     -> Math.log(arg(c, args, 0, values, defs));
            case "log10"  -> Math.log10(arg(c, args, 0, values, defs));
            case "sqrt"   -> Math.sqrt(arg(c, args, 0, values, defs));
            case "sin"    -> Math.sin(arg(c, args, 0, values, defs));
            case "cos"    -> Math.cos(arg(c, args, 0, values, defs));
            case "tan"    -> Math.tan(arg(c, args, 0, values, defs));
            case "real"   -> arg(c, args, 0, values, defs);
            case "imag"   -> 0.0;
            case "arcsin" -> Math.asin(arg(c, args, 0, values, defs));
            case "arccos" -> Math.acos(arg(c, args, 0, values, defs));
            case "arctan" -> Math.atan(arg(c, args, 0, values, defs));
            case "atan2"  -> Math.atan2(arg(c, args, 0, values, defs), arg(c, args, 1, values, defs));
            case "min"    -> args.stream().mapToDouble(a -> eval(a, values, defs)).min()
                    .orElseThrow(() -> new IllegalStateException("min expects at least 1 argument"));
            case "max"    -> args.stream().mapToDouble(a -> eval(a, values, defs)).max()
                    .orElseThrow(() -> new IllegalStateException("max expects at least 1 argument"));
            case "sum"    -> args.stream().mapToDouble(a -> eval(a, values, defs)).sum();
            case "average", "avg" -> args.stream().mapToDouble(a -> eval(a, values, defs))
                    .average().orElse(0.0);
            case "integral" -> integralQuadrature(c, values, defs);

            // Bitwise operations
            case "bitand" -> (double) ((long) arg(c, args, 0, values, defs) & (long) arg(c, args, 1, values, defs));
            case "bitor"  -> (double) ((long) arg(c, args, 0, values, defs) | (long) arg(c, args, 1, values, defs));
            case "bitxor" -> (double) ((long) arg(c, args, 0, values, defs) ^ (long) arg(c, args, 1, values, defs));
            case "bitnot" -> (double) (~((long) arg(c, args, 0, values, defs)));
            case "bitshiftl" -> (double) ((long) arg(c, args, 0, values, defs) << (int) arg(c, args, 1, values, defs));
            case "bitshiftr" -> (double) ((long) arg(c, args, 0, values, defs) >> (int) arg(c, args, 1, values, defs));

            // CS & Number theory
            case "mod" -> arg(c, args, 0, values, defs) % arg(c, args, 1, values, defs);
            case "gcd" -> (double) org.apache.commons.math3.util.ArithmeticUtils.gcd((long) arg(c, args, 0, values, defs), (long) arg(c, args, 1, values, defs));
            case "lcm" -> (double) org.apache.commons.math3.util.ArithmeticUtils.lcm((long) arg(c, args, 0, values, defs), (long) arg(c, args, 1, values, defs));

            // Special math functions
            case "erf"     -> org.apache.commons.math3.special.Erf.erf(arg(c, args, 0, values, defs));
            case "erfc"    -> org.apache.commons.math3.special.Erf.erfc(arg(c, args, 0, values, defs));
            case "erfinv"  -> org.apache.commons.math3.special.Erf.erfInv(arg(c, args, 0, values, defs));
            case "gamma"   -> org.apache.commons.math3.special.Gamma.gamma(arg(c, args, 0, values, defs));
            case "loggamma"-> org.apache.commons.math3.special.Gamma.logGamma(arg(c, args, 0, values, defs));
            case "digamma" -> org.apache.commons.math3.special.Gamma.digamma(arg(c, args, 0, values, defs));
            case "beta"    -> Math.exp(org.apache.commons.math3.special.Beta.logBeta(arg(c, args, 0, values, defs), arg(c, args, 1, values, defs)));
            case "besselj" -> org.apache.commons.math3.special.BesselJ.value(arg(c, args, 1, values, defs), arg(c, args, 0, values, defs));
            case "besseli" -> besselI(arg(c, args, 1, values, defs), arg(c, args, 0, values, defs));

            // Base conversion: BaseConvert('FF', 16, 10) -> 255
            case "baseconvert" -> evalBaseConvert(c, values, defs);

            default -> throw new IllegalStateException("Unknown function: " + c.function());
        };
    }

    /**
     * Evaluates a synthetic eigen$val$<k>$<n> or eigen$vec$<i>$<k>$<n> call.
     * Eigenpairs are sorted ascending by eigenvalue; eigenvectors are unit-normalized
     * with their largest-magnitude component made positive so results are deterministic.
     */
    private static double evalEigen(Expr.Call c, Map<String, Double> values, Map<String, ProcDef> defs) {
        String[] parts = c.function().split("\\$");
        boolean wantVector = parts[1].equals("vec");
        int n = Integer.parseInt(parts[parts.length - 1]);
        double[][] m = new double[n][n];
        List<Expr> args = c.args();
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < n; j++) {
                m[i][j] = eval(args.get(i * n + j), values, defs);
            }
        }
        EigenDecomposition ed = new EigenDecomposition(new Array2DRowRealMatrix(m, false));
        if (ed.hasComplexEigenvalues()) {
            throw new IllegalStateException(
                    "Matrix has complex eigenvalues; Eigenvalues/Eigen support real spectra only "
                    + "(symmetric matrices always qualify).");
        }
        Integer[] order = new Integer[n];
        for (int i = 0; i < n; i++) {
            order[i] = i;
        }
        java.util.Arrays.sort(order, Comparator.comparingDouble(ed::getRealEigenvalue));
        int k = Integer.parseInt(parts[2 + (wantVector ? 1 : 0)]);
        if (!wantVector) {
            return ed.getRealEigenvalue(order[k]);
        }
        int component = Integer.parseInt(parts[2]);
        RealVector v = ed.getEigenvector(order[k]);
        v = v.mapDivide(v.getNorm());
        int maxIdx = 0;
        for (int i = 1; i < n; i++) {
            if (Math.abs(v.getEntry(i)) > Math.abs(v.getEntry(maxIdx))) {
                maxIdx = i;
            }
        }
        if (v.getEntry(maxIdx) < 0) {
            v = v.mapMultiply(-1.0);
        }
        return v.getEntry(component);
    }

    /**
     * Quadrature for an Integral whose limits contain unknowns (see
     * IntegralSolver.inlinedEquation): by construction the integrand is
     * closed-form in the integration variable, so the integral is an
     * ordinary function of its limits, re-evaluated at every Newton
     * residual evaluation. Adaptive Simpson is exact for the polynomial
     * c_p fits of combustion problems and refines only where needed
     * otherwise; the noise floor must stay far below the perturbations of
     * the numerical Jacobian, hence the tight tolerance.
     */
    private static final double SIMPSON_REL_TOL = 1e-12;
    private static final int SIMPSON_MAX_DEPTH = 24;

    private static double integralQuadrature(Expr.Call c, Map<String, Double> values,
                                             Map<String, ProcDef> defs) {
        List<Expr> args = c.args();
        if (args.size() < 4 || !(args.get(1) instanceof Expr.Var(String varName))) {
            throw new IllegalStateException(
                    "Integral expects Integral(f, t, lower, upper[, step]).");
        }
        double lower = eval(args.get(2), values, defs);
        double upper = eval(args.get(3), values, defs);
        if (lower == upper) {
            return 0.0;
        }
        boolean had = values.containsKey(varName);
        Double saved = had ? values.get(varName) : null;
        try {
            Expr f = args.get(0);
            SimpsonContext context = new SimpsonContext(f, varName, values, defs);
            double fa = context.evalAt(lower);
            double fm = context.evalAt((lower + upper) / 2.0);
            double fb = context.evalAt(upper);
            double whole = (upper - lower) / 6.0 * (fa + 4.0 * fm + fb);
            return context.adaptiveSimpson(lower, upper, fa, fm, fb, whole, SIMPSON_MAX_DEPTH);
        } finally {
            if (had) {
                values.put(varName, saved);
            } else {
                values.remove(varName);
            }
        }
    }

    private static class SimpsonContext {
        final Expr f;
        final String varName;
        final Map<String, Double> values;
        final Map<String, ProcDef> defs;

        SimpsonContext(Expr f, String varName, Map<String, Double> values, Map<String, ProcDef> defs) {
            this.f = f;
            this.varName = varName;
            this.values = values;
            this.defs = defs;
        }

        double evalAt(double t) {
            values.put(varName, t);
            return eval(f, values, defs);
        }

        double adaptiveSimpson(double a, double b, double fa, double fm, double fb, double whole, int depth) {
            double m = (a + b) / 2.0;
            double lm = (a + m) / 2.0;
            double rm = (m + b) / 2.0;
            double flm = evalAt(lm);
            double frm = evalAt(rm);
            double left = (m - a) / 6.0 * (fa + 4.0 * flm + fm);
            double right = (b - m) / 6.0 * (fm + 4.0 * frm + fb);
            double halves = left + right;
            double delta = halves - whole;
            if (depth <= 0
                    || Math.abs(delta) <= 15.0 * SIMPSON_REL_TOL * Math.max(Math.abs(halves), 1.0)) {
                return halves + delta / 15.0;
            }
            return adaptiveSimpson(a, m, fa, flm, fm, left, depth - 1)
                    + adaptiveSimpson(m, b, fm, frm, fb, right, depth - 1);
        }
    }

    private static double arg(Expr.Call c, List<Expr> args, int i,
                               Map<String, Double> values, Map<String, ProcDef> defs) {
        if (i >= args.size()) {
            throw new IllegalStateException(
                    "Function " + c.function() + " expects at least " + (i + 1) + " argument(s)");
        }
        return eval(args.get(i), values, defs);
    }

    /**
     * Modified Bessel function of the first kind I_order(x), via the ascending
     * series with log-space terms (overflow-safe up to x ≈ 700). Commons Math
     * provides BesselJ but not BesselI.
     */
    static double besselI(double order, double x) {
        if (x < 0) {
            if (order != Math.rint(order)) {
                throw new IllegalStateException(
                        "BesselI of a negative argument requires an integer order.");
            }
            double sign = ((long) Math.rint(order)) % 2 == 0 ? 1.0 : -1.0;
            return sign * besselI(order, -x);
        }
        if (order < 0) {
            if (order != Math.rint(order)) {
                throw new IllegalStateException(
                        "BesselI supports integer or non-negative orders, got " + order + ".");
            }
            order = -order; // I_{-n}(x) = I_n(x) for integer n
        }
        if (x == 0.0) {
            return order == 0.0 ? 1.0 : 0.0;
        }
        double lnHalfX = Math.log(x / 2.0);
        double sum = 0.0;
        for (int k = 0; k < 2000; k++) {
            double lnTerm = (2.0 * k + order) * lnHalfX
                    - org.apache.commons.math3.special.Gamma.logGamma(k + 1.0)
                    - org.apache.commons.math3.special.Gamma.logGamma(k + order + 1.0);
            double term = Math.exp(lnTerm);
            sum += term;
            if (term < sum * 1e-17 && k > x / 2.0) {
                break;
            }
        }
        return sum;
    }

    /**
     * BaseConvert(digits, fromBase, toBase): converts a number between bases 2-36.
     * The digits argument is a string literal (e.g. 'FF') or a numeric expression
     * whose integer decimal representation is used. The result is returned as the
     * number whose decimal digits spell the converted value, so it must contain
     * only the digits 0-9 (i.e. toBase <= 10, or a value small enough to avoid
     * letter digits).
     */
    private static double evalBaseConvert(Expr.Call c, Map<String, Double> values, Map<String, ProcDef> defs) {
        if (c.args().size() != 3) {
            throw new IllegalStateException(
                    "BaseConvert expects 3 arguments: BaseConvert('digits', fromBase, toBase).");
        }
        Expr first = c.args().get(0);
        String digits;
        if (first instanceof Expr.Str s) {
            digits = s.value().trim();
        } else {
            double v = eval(first, values, defs);
            if (v != Math.rint(v) || Double.isInfinite(v)) {
                throw new IllegalStateException(
                        "BaseConvert input must be an integer, got: " + v);
            }
            digits = Long.toString((long) v);
        }
        int fromBase = (int) Math.rint(eval(c.args().get(1), values, defs));
        int toBase = (int) Math.rint(eval(c.args().get(2), values, defs));
        if (fromBase < 2 || fromBase > 36 || toBase < 2 || toBase > 36) {
            throw new IllegalStateException(
                    "BaseConvert bases must be between 2 and 36, got " + fromBase + " and " + toBase + ".");
        }
        long value;
        try {
            value = Long.parseLong(digits, fromBase);
        } catch (NumberFormatException e) {
            throw new IllegalStateException(
                    "'" + digits + "' is not a valid base-" + fromBase + " number.");
        }
        String converted = Long.toString(value, toBase);
        if (!converted.matches("-?[0-9]+")) {
            throw new IllegalStateException(
                    "BaseConvert result '" + converted.toUpperCase() + "' in base " + toBase
                    + " contains letter digits and cannot be represented as a number; use toBase <= 10.");
        }
        return Double.parseDouble(converted);
    }

    /**
     * Extracts a string value from an expression.
     * Supports {@link Expr.Str} (quoted strings) and {@link Expr.Var}
     * (backward compatibility: bare identifiers treated as string labels).
     */
    public static String evalString(Expr e) {
        if (e instanceof Expr.Str s) return s.value();
        if (e instanceof Expr.Var v) return v.name();  // backward compat: bare idents as strings
        throw new IllegalStateException("Expected a string argument, got: " + e);
    }
}
