package com.frees.backend.ast;

import java.util.List;
import java.util.Map;

/** Evaluates an expression AST against current variable values. */
public final class Evaluator {

    private Evaluator() {}

    public static double eval(Expr e, Map<String, Double> values) {
        return eval(e, values, Map.of());
    }

    public static double eval(Expr e, Map<String, Double> values, Map<String, ProcDef> defs) {
        return switch (e) {
            case Expr.Num n -> n.value();
            case Expr.Var v -> {
                Double value = values.get(v.name());
                if (value == null) {
                    throw new IllegalStateException("Variable has no value: " + v.name());
                }
                yield value;
            }
            case Expr.Neg neg -> -eval(neg.operand(), values, defs);
            case Expr.BinOp b -> {
                double l = eval(b.left(), values, defs);
                double r = eval(b.right(), values, defs);
                yield switch (b.op()) {
                    case '+' -> l + r;
                    case '-' -> l - r;
                    case '*' -> l * r;
                    case '/' -> l / r;
                    case '^' -> Math.pow(l, r);
                    default -> throw new IllegalStateException("Unknown operator: " + b.op());
                };
            }
            case Expr.Call c -> evalCall(c, values, defs);
            case Expr.ArrayAccess aa -> throw new IllegalStateException("ArrayAccess cannot be evaluated directly: " + aa);
            case Expr.Range r -> throw new IllegalStateException("Range cannot be evaluated directly: " + r);
            case Expr.ArrayLiteral al -> throw new IllegalStateException("ArrayLiteral cannot be evaluated directly: " + al);
            case Expr.Compare cmp -> {
                double l = eval(cmp.left(), values, defs);
                double r = eval(cmp.right(), values, defs);
                boolean result = switch (cmp.op()) {
                    case "<"  -> l < r;
                    case ">"  -> l > r;
                    case "<=" -> l <= r;
                    case ">=" -> l >= r;
                    case "<>" -> l != r;
                    case "="  -> l == r;
                    default -> throw new IllegalStateException("Unknown comparison operator: " + cmp.op());
                };
                yield result ? 1.0 : 0.0;
            }
            case Expr.Logical log -> {
                double l = eval(log.left(), values, defs);
                double r = eval(log.right(), values, defs);
                boolean result = switch (log.op()) {
                    case "and" -> l != 0.0 && r != 0.0;
                    case "or"  -> l != 0.0 || r != 0.0;
                    default -> throw new IllegalStateException("Unknown logical operator: " + log.op());
                };
                yield result ? 1.0 : 0.0;
            }
            case Expr.Not not -> eval(not.operand(), values, defs) == 0.0 ? 1.0 : 0.0;
        };
    }

    private static double evalCall(Expr.Call c, Map<String, Double> values, Map<String, ProcDef> defs) {
        // Dispatch to user-defined FUNCTION
        ProcDef def = defs.get(c.function());
        if (def instanceof ProcDef.FunctionDef fd) {
            List<Double> args = c.args().stream()
                    .map(a -> eval(a, values, defs))
                    .toList();
            return new com.frees.backend.parser.ProcedureEvaluator(defs).callFunction(fd, args, values);
        }

        // Synthetic procedure output call: proc$<name>$<outputIndex>(inputs...)
        // Generated by EquationParser when flattening CALL statements.
        if (c.function().startsWith("proc$")) {
            String[] parts = c.function().split("\\$", 3);
            if (parts.length == 3) {
                String procName = parts[1];
                int outputIndex = Integer.parseInt(parts[2]);
                ProcDef procDef = defs.get(procName);
                if (procDef instanceof ProcDef.ProcedureDef pd) {
                    List<Double> inputVals = c.args().stream()
                            .map(a -> eval(a, values, defs))
                            .toList();
                    Map<String, Double> outputs =
                            new com.frees.backend.parser.ProcedureEvaluator(defs)
                                    .callProcedure(pd, inputVals, values);
                    String outKey = pd.outputs().get(outputIndex).toLowerCase();
                    return outputs.get(outKey);
                }
            }
        }

        // Built-in functions
        List<Expr> args = c.args();
        return switch (c.function()) {
            case "abs"    -> Math.abs(arg(c, args, 0, values, defs));
            case "exp"    -> Math.exp(arg(c, args, 0, values, defs));
            case "ln"     -> Math.log(arg(c, args, 0, values, defs));
            case "log10"  -> Math.log10(arg(c, args, 0, values, defs));
            case "sqrt"   -> Math.sqrt(arg(c, args, 0, values, defs));
            case "sin"    -> Math.sin(arg(c, args, 0, values, defs));
            case "cos"    -> Math.cos(arg(c, args, 0, values, defs));
            case "tan"    -> Math.tan(arg(c, args, 0, values, defs));
            case "arcsin" -> Math.asin(arg(c, args, 0, values, defs));
            case "arccos" -> Math.acos(arg(c, args, 0, values, defs));
            case "arctan" -> Math.atan(arg(c, args, 0, values, defs));
            case "atan2"  -> Math.atan2(arg(c, args, 0, values, defs), arg(c, args, 1, values, defs));
            case "min"    -> args.stream().mapToDouble(a -> eval(a, values, defs)).min()
                    .orElseThrow(() -> new IllegalStateException("min expects at least 1 argument"));
            case "max"    -> args.stream().mapToDouble(a -> eval(a, values, defs)).max()
                    .orElseThrow(() -> new IllegalStateException("max expects at least 1 argument"));
            case "sum"    -> args.stream().mapToDouble(a -> eval(a, values, defs)).sum();
            case "average", "avg" -> args.stream().mapToDouble(a -> eval(a, values, defs))
                    .average().orElse(0.0);
            default -> throw new IllegalStateException("Unknown function: " + c.function());
        };
    }

    private static double arg(Expr.Call c, List<Expr> args, int i,
                               Map<String, Double> values, Map<String, ProcDef> defs) {
        if (i >= args.size()) {
            throw new IllegalStateException(
                    "Function " + c.function() + " expects at least " + (i + 1) + " argument(s)");
        }
        return eval(args.get(i), values, defs);
    }
}
