package com.frees.backend.ast;

import java.util.List;
import java.util.Map;

/** Evaluates an expression AST against current variable values. */
public final class Evaluator {

    private Evaluator() {}

    public static double eval(Expr e, Map<String, Double> values) {
        return eval(e, values, Map.of());
    }

    public static double eval(Expr e, Map<String, Double> values, Map<String, ProcDef> defs) {
        return switch (e) {
            case Expr.Num n -> n.value();
            case Expr.Var v -> {
                Double value = values.get(v.name());
                if (value == null) {
                    throw new IllegalStateException("Variable has no value: " + v.name());
                }
                yield value;
            }
            case Expr.Neg neg -> -eval(neg.operand(), values, defs);
            case Expr.BinOp b -> {
                double l = eval(b.left(), values, defs);
                double r = eval(b.right(), values, defs);
                yield switch (b.op()) {
                    case '+' -> l + r;
                    case '-' -> l - r;
                    case '*' -> l * r;
                    case '/' -> l / r;
                    case '^' -> Math.pow(l, r);
                    default -> throw new IllegalStateException("Unknown operator: " + b.op());
                };
            }
            case Expr.Call c -> evalCall(c, values, defs);
            case Expr.ArrayAccess aa -> throw new IllegalStateException("ArrayAccess cannot be evaluated directly: " + aa);
            case Expr.Range r -> throw new IllegalStateException("Range cannot be evaluated directly: " + r);
            case Expr.ArrayLiteral al -> throw new IllegalStateException("ArrayLiteral cannot be evaluated directly: " + al);
            case Expr.Compare cmp -> {
                double l = eval(cmp.left(), values, defs);
                double r = eval(cmp.right(), values, defs);
                boolean result = switch (cmp.op()) {
                    case "<"  -> l < r;
                    case ">"  -> l > r;
                    case "<=" -> l <= r;
                    case ">=" -> l >= r;
                    case "<>" -> l != r;
                    case "="  -> l == r;
                    default -> throw new IllegalStateException("Unknown comparison operator: " + cmp.op());
                };
                yield result ? 1.0 : 0.0;
            }
            case Expr.Logical log -> {
                double l = eval(log.left(), values, defs);
                double r = eval(log.right(), values, defs);
                boolean result = switch (log.op()) {
                    case "and" -> l != 0.0 && r != 0.0;
                    case "or"  -> l != 0.0 || r != 0.0;
                    default -> throw new IllegalStateException("Unknown logical operator: " + log.op());
                };
                yield result ? 1.0 : 0.0;
            }
            case Expr.Not not -> eval(not.operand(), values, defs) == 0.0 ? 1.0 : 0.0;
        };
    }

    private static double evalCall(Expr.Call c, Map<String, Double> values, Map<String, ProcDef> defs) {
        // Dispatch to user-defined FUNCTION
        ProcDef def = defs.get(c.function());
        if (def instanceof ProcDef.FunctionDef fd) {
            List<Double> args = c.args().stream()
                    .map(a -> eval(a, values, defs))
                    .toList();
            return new com.frees.backend.parser.ProcedureEvaluator(defs).callFunction(fd, args, values);
        }

        // Fluid property call: prop$<output>$<fluid>$<ind1>$<ind2>(values...)
        // Generated by AstBuilder from e.g. Enthalpy(R134a, T=T1, x=1).
        if (c.function().startsWith(com.frees.backend.props.PropertyFunctions.PREFIX)) {
            List<Double> propArgs = c.args().stream()
                    .map(a -> eval(a, values, defs))
                    .toList();
            return com.frees.backend.props.PropertyFunctions.evaluate(c.function(), propArgs);
        }

        // Synthetic procedure output call: proc$<name>$<outputIndex>(inputs...)
        // Generated by EquationParser when flattening CALL statements.
        if (c.function().startsWith("proc$")) {
            String[] parts = c.function().split("\\$", 3);
            if (parts.length == 3) {
                String procName = parts[1];
                int outputIndex = Integer.parseInt(parts[2]);
                ProcDef procDef = defs.get(procName);
                if (procDef instanceof ProcDef.ProcedureDef pd) {
                    List<Double> inputVals = c.args().stream()
                            .map(a -> eval(a, values, defs))
                            .toList();
                    Map<String, Double> outputs =
                            new com.frees.backend.parser.ProcedureEvaluator(defs)
                                    .callProcedure(pd, inputVals, values);
                    String outKey = pd.outputs().get(outputIndex).toLowerCase();
                    return outputs.get(outKey);
                }
            }
        }

        // Built-in functions
        List<Expr> args = c.args();
        return switch (c.function()) {
            case "abs"    -> Math.abs(arg(c, args, 0, values, defs));
            case "exp"    -> Math.exp(arg(c, args, 0, values, defs));
            case "ln"     -> Math.log(arg(c, args, 0, values, defs));
            case "log10"  -> Math.log10(arg(c, args, 0, values, defs));
            case "sqrt"   -> Math.sqrt(arg(c, args, 0, values, defs));
            case "sin"    -> Math.sin(arg(c, args, 0, values, defs));
            case "cos"    -> Math.cos(arg(c, args, 0, values, defs));
            case "tan"    -> Math.tan(arg(c, args, 0, values, defs));
            case "real"   -> arg(c, args, 0, values, defs);
            case "imag"   -> 0.0;
            case "arcsin" -> Math.asin(arg(c, args, 0, values, defs));
            case "arccos" -> Math.acos(arg(c, args, 0, values, defs));
            case "arctan" -> Math.atan(arg(c, args, 0, values, defs));
            case "atan2"  -> Math.atan2(arg(c, args, 0, values, defs), arg(c, args, 1, values, defs));
            case "min"    -> args.stream().mapToDouble(a -> eval(a, values, defs)).min()
                    .orElseThrow(() -> new IllegalStateException("min expects at least 1 argument"));
            case "max"    -> args.stream().mapToDouble(a -> eval(a, values, defs)).max()
                    .orElseThrow(() -> new IllegalStateException("max expects at least 1 argument"));
            case "sum"    -> args.stream().mapToDouble(a -> eval(a, values, defs)).sum();
            case "average", "avg" -> args.stream().mapToDouble(a -> eval(a, values, defs))
                    .average().orElse(0.0);
            case "integral" -> integralQuadrature(c, values, defs);
            default -> throw new IllegalStateException("Unknown function: " + c.function());
        };
    }

    /**
     * Quadrature for an Integral whose limits contain unknowns (see
     * IntegralSolver.inlinedEquation): by construction the integrand is
     * closed-form in the integration variable, so the integral is an
     * ordinary function of its limits, re-evaluated at every Newton
     * residual evaluation. Adaptive Simpson is exact for the polynomial
     * c_p fits of combustion problems and refines only where needed
     * otherwise; the noise floor must stay far below the perturbations of
     * the numerical Jacobian, hence the tight tolerance.
     */
    private static final double SIMPSON_REL_TOL = 1e-12;
    private static final int SIMPSON_MAX_DEPTH = 24;

    private static double integralQuadrature(Expr.Call c, Map<String, Double> values,
                                             Map<String, ProcDef> defs) {
        List<Expr> args = c.args();
        if (args.size() < 4 || !(args.get(1) instanceof Expr.Var t)) {
            throw new IllegalStateException(
                    "Integral expects Integral(f, t, lower, upper[, step]).");
        }
        double lower = eval(args.get(2), values, defs);
        double upper = eval(args.get(3), values, defs);
        if (lower == upper) {
            return 0.0;
        }
        String var = t.name();
        boolean had = values.containsKey(var);
        Double saved = had ? values.get(var) : null;
        try {
            Expr f = args.get(0);
            double fa = evalAt(f, var, lower, values, defs);
            double fm = evalAt(f, var, (lower + upper) / 2.0, values, defs);
            double fb = evalAt(f, var, upper, values, defs);
            double whole = (upper - lower) / 6.0 * (fa + 4.0 * fm + fb);
            return adaptiveSimpson(f, var, lower, upper, fa, fm, fb, whole,
                    SIMPSON_MAX_DEPTH, values, defs);
        } finally {
            if (had) {
                values.put(var, saved);
            } else {
                values.remove(var);
            }
        }
    }

    private static double evalAt(Expr f, String var, double t,
                                 Map<String, Double> values, Map<String, ProcDef> defs) {
        values.put(var, t);
        return eval(f, values, defs);
    }

    private static double adaptiveSimpson(Expr f, String var, double a, double b,
                                          double fa, double fm, double fb, double whole,
                                          int depth, Map<String, Double> values,
                                          Map<String, ProcDef> defs) {
        double m = (a + b) / 2.0;
        double lm = (a + m) / 2.0;
        double rm = (m + b) / 2.0;
        double flm = evalAt(f, var, lm, values, defs);
        double frm = evalAt(f, var, rm, values, defs);
        double left = (m - a) / 6.0 * (fa + 4.0 * flm + fm);
        double right = (b - m) / 6.0 * (fm + 4.0 * frm + fb);
        double halves = left + right;
        double delta = halves - whole;
        if (depth <= 0
                || Math.abs(delta) <= 15.0 * SIMPSON_REL_TOL * Math.max(Math.abs(halves), 1.0)) {
            return halves + delta / 15.0;
        }
        return adaptiveSimpson(f, var, a, m, fa, flm, fm, left, depth - 1, values, defs)
                + adaptiveSimpson(f, var, m, b, fm, frm, fb, right, depth - 1, values, defs);
    }

    private static double arg(Expr.Call c, List<Expr> args, int i,
                               Map<String, Double> values, Map<String, ProcDef> defs) {
        if (i >= args.size()) {
            throw new IllegalStateException(
                    "Function " + c.function() + " expects at least " + (i + 1) + " argument(s)");
        }
        return eval(args.get(i), values, defs);
    }
}
