import { requireValidTable, tableShape } from './tableValidation'
import { CheckResponse, FunctionTableDto, OdeTableDto, ParametricTableDto, TableRowResult, TableStats } from './api'

/** One parametric-table run: a stable identity plus the cell drafts.
 * (Lived in ParametricTableTab until the Mantine grid was retired in favour
 * of the Univer Tables workbook — Phase 4 of the unification plan.) */
export interface ParamRow {
  id: string
  values: Record<string, string>
}

export function newParamRow(): ParamRow {
  return { id: crypto.randomUUID(), values: {} }
}

// ---------------------------------------------------------------------------
// Tables (Epic 8): the Tables window manages any number of
// Parametric Tables (run tables) and Function Tables (tabulated functions from
// the Graph Digitizer or entered manually). A Function Table's name is the
// function name callable in equations; its column names are the arguments —
// the first column is the lookup argument. If it has a curve family parameter,
// the rest are curves with the family parameter value in the header
// (e.g. T = 100, 200, ...).
// ---------------------------------------------------------------------------

export interface TableOperationProvenance {
  operation: 'filter' | 'transform' | 'groupby' | 'rolling' | 'join'
  sourceTableIds: string[]
  sourceTableNames: string[]
  timestamp: number
  description: string
  sourceRowCount: number
  resultRowCount: number
  rejectedRowCount?: number
  duplicateKeyCount?: number
  extrapolatedCount?: number
  details?: Record<string, unknown>
}

export interface ParamTableSpec {
  id: string
  kind: 'parametric'
  recoveredContent?: unknown
  resultRevision?: number
  runStatus?: 'not-run' | 'stale' | 'running' | 'completed' | 'cancelled'
  name: string
  vars: string[]
  rows: ParamRow[]
  results: TableRowResult[]
  stats: TableStats | null
  checkResult: CheckResponse | null
  checkMessage: string
  source?: 'code' | 'gui'
  /** Set when this "parametric" table was produced from a DYNAMIC/ODE block
   * rather than a PARAMETRIC block, so the UI can describe it correctly. */
  origin?: 'ode'
  /** Sparse formula overlay (contract f) for input cells edited as a bound
   * sheet in the Tables workbook — same mechanics as FunctionTableSpec. */
  formulas?: Record<string, string>
  /** Preserved legacy overlays with no current cell binding after structural edits. */
  detachedFormulas?: Record<string, string>[]
  /** Per-column SI units (column name → unit), for read-only code/ODE tables
   * whose columns are not solved scalars: used for grid headers and plot axes. */
  columnUnits?: Record<string, string>
  /** Data provenance metadata recording operation, source tables, and row policies. */
  provenance?: TableOperationProvenance
}

interface CurveRow {
  x: string
  ys: string[]
}

export interface FunctionTableSpec {
  id: string
  kind: 'function'
  recoveredContent?: unknown
  name: string // function name callable in equations
  argName: string // first column: the lookup argument, e.g. Re
  paramName: string // family parameter name, e.g. T ('' for a lone curve)
  xLog: boolean
  yLog: boolean
  columns: string[] // family parameter value per curve column
  rows: CurveRow[]
  is1D?: boolean // if true, it represents a function without a curve family/parameter
  /** Cells generated by Fill missing, as row/curve indices. */
  interpolatedCells?: { row: number; column: number }[]
  // 'code' tables are parsed from TABLE ... END blocks in the editor text and
  // are shown read-only (the editor text is their source of truth). Undefined
  // / 'gui' tables are created and edited in the Tables window.
  source?: 'code' | 'gui'
  /** Sparse formula overlay (contract f of the table-spreadsheet unification
   * plan): A1 cell ref → Univer formula string for data cells the user
   * entered as formulas in the bound sheet. Row cells keep the last computed
   * value (the solver wire path reads only those); this overlay is re-applied
   * as `f`-only cells at materialization so formulas survive reloads and
   * recompute. Optional — absent on tables never edited as sheets. */
  formulas?: Record<string, string>
  /** Preserved legacy overlays with no current cell binding after structural edits. */
  detachedFormulas?: Record<string, string>[]
  /** Last conversion that produced this table, when it came from CSV/sweep/fit. */
  conversion?: FunctionConversion
  /** Lookup-argument unit as written; unknown/blank is not assumed SI. */
  argUnit?: string
  /** Family-parameter unit, when the table is a curve family. */
  paramUnit?: string
  /** Output (Y) unit as written. */
  outputUnit?: string
}

/** Provenance of a GUI function produced from CSV, sweep columns, or a fit. */
export interface FunctionConversion {
  valueSource?: 'mixed' | 'raw' | 'solved'
  reduction?: 'decimate' | 'trim'
  xMin?: number
  xMax?: number
  sourceCount: number
  invalidCount: number
  duplicateCount: number
  uniqueCount: number
  trimmedCount: number
  reducedCount: number
  retainedCount: number
}

export type TableSpec = ParamTableSpec | FunctionTableSpec

export function detachLegacyFormulas<T extends TableSpec>(table: T): T {
  if (!table.formulas || Object.keys(table.formulas).length === 0) return table
  return { ...table, formulas: undefined, detachedFormulas: [...(table.detachedFormulas ?? []), table.formulas] }
}

export function uniqueTableName(base: string, tables: TableSpec[]): string {
  const occupied = new Set(tables.map((t) => t.name.toLowerCase()))
  let name = base
  for (let i = 2; occupied.has(name.toLowerCase()); i++) name = `${base}${i}`
  return name
}

/** Keep malformed imports recoverable without feeding their shape to the grid. */
export function normalizeTables(raw: unknown): TableSpec[] {
  if (!Array.isArray(raw)) return []
  const ids = new Set<string>()
  return raw.map((value, i) => {
    if (!tableShape(value) || ids.has(value.id)) return {
      ...newParamTable([]), name: `Recovered table ${i + 1}`, recoveredContent: value,
    }
    ids.add(value.id)
    return value.kind === 'parametric' ? { ...value, results: [], stats: null, checkResult: null, checkMessage: '', runStatus: 'not-run' } : value
  })
}

let tableCounter = 1

export function newTableId(): string {
  return `table-${Date.now()}-${tableCounter++}`
}

export function newParamTable(existing: TableSpec[]): ParamTableSpec {
  const count = existing.filter((t) => t.kind === 'parametric').length
  return {
    id: newTableId(),
    kind: 'parametric',
    name: uniqueTableName(`Parametric ${count + 1}`, existing),
    vars: [],
    rows: [newParamRow(), newParamRow(), newParamRow()],
    results: [],
    stats: null,
    checkResult: null,
    checkMessage: '',
  }
}

export function newFunctionTable(existing: TableSpec[], is1D: boolean): FunctionTableSpec {
  const count = existing.filter((t) => t.kind === 'function').length
  return {
    id: newTableId(),
    kind: 'function',
    name: uniqueTableName(`func${count + 1}`, existing),
    argName: 'x',
    paramName: '',
    xLog: false,
    yLog: false,
    columns: is1D ? [''] : ['100', '200'],
    rows: Array.from({ length: 5 }, () => ({ x: '', ys: is1D ? [''] : ['', ''] })),
    is1D,
  }
}

/** Function tables in solver wire format; blank cells are simply omitted.
 * Code-sourced tables are skipped — the backend parses them from the editor
 * text itself, so re-sending them would be redundant. */
export function toFunctionTableDtos(tables: TableSpec[]): FunctionTableDto[] {
  const dtos: FunctionTableDto[] = []
  const names = new Set<string>()
  for (const table of tables) {
    if (table.kind !== 'function') continue
    if (table.source === 'code') continue
    requireValidTable(table)
    const key = table.name.trim().toLowerCase()
    if (names.has(key)) throw new Error(`Duplicate function table name: ${table.name}`)
    names.add(key)
    const curves = table.columns.map((paramRaw, j) => {
      const points: number[][] = []
      for (const row of table.rows) {
        const x = Number(row.x)
        const y = Number(row.ys[j])
        if (row.x.trim() !== '' && (row.ys[j] ?? '').trim() !== '' && Number.isFinite(x) && Number.isFinite(y)) {
          points.push([x, y])
        }
      }
      const param = Number(paramRaw)
      return {
        param: paramRaw.trim() !== '' && Number.isFinite(param) ? param : null,
        points,
      }
    })
    if (curves.some((c) => c.points.length > 0)) {
      const argNames = [table.argName, table.paramName].filter((a) => a.trim() !== '')
      const argUnits = [table.argUnit, table.paramUnit]
        .slice(0, argNames.length)
        .map((u) => (u && u.trim() && u.trim() !== '-' ? u.trim() : null))
      dtos.push({
        name: table.name.trim(),
        argNames,
        xLog: table.xLog,
        yLog: table.yLog,
        curves,
        outputUnit: table.outputUnit?.trim() || null,
        argUnits: argUnits.some((u) => u) ? argUnits : null,
      })
    }
  }
  return dtos
}

function scaleVal(v: number, log: boolean): number {
  return log ? Math.log10(v) : v
}

function unscaleVal(v: number, log: boolean): number {
  return log ? Math.pow(10, v) : v
}

function fmtCell(v: number): string {
  return String(v)
}

/**
 * Fill missing: every blank cell whose row has an x inside a curve's
 * tabulated span is interpolated from that curve's known points (linear,
 * in log space for log axes). Cells outside the span stay blank — the
 * chart carries no information there.
 */
export function fillMissingCells(table: FunctionTableSpec): FunctionTableSpec {
  const invalid: string[] = []
  table.rows.forEach((row, i) => {
    if (row.x.trim() && (!Number.isFinite(Number(row.x)) || (table.xLog && Number(row.x) <= 0))) invalid.push(`row ${i + 1}, X`)
    row.ys.forEach((y, j) => {
      if (y.trim() && (!Number.isFinite(Number(y)) || (table.yLog && Number(y) <= 0))) invalid.push(`row ${i + 1}, curve ${j + 1}`)
    })
  })
  if (invalid.length) throw new Error(`Fill requires finite values and positive logarithmic coordinates: ${invalid.join('; ')}`)
  const rows = table.rows.map((r) => ({ x: r.x, ys: [...r.ys] }))
  for (let j = 0; j < table.columns.length; j++) {
    const known = collectKnownPoints(rows, j)
    if (known.length === 0) continue
    interpolateColumn(rows, j, known, table)
  }
  const interpolatedCells = [...(table.interpolatedCells ?? [])]
  rows.forEach((row, i) => row.ys.forEach((y, j) => {
    if (y !== '' && !(table.rows[i].ys[j] ?? '').trim()) interpolatedCells.push({ row: i, column: j })
  }))
  return { ...table, rows, interpolatedCells }
}

type FillRow = { x: string; ys: string[] }

/** The finite (x, y) samples present in column {@code j}, sorted ascending by x. */
function collectKnownPoints(rows: FillRow[], j: number): { x: number; y: number }[] {
  const known: { x: number; y: number }[] = []
  for (const row of rows) {
    const x = Number(row.x)
    const y = Number(row.ys[j])
    if (row.x.trim() !== '' && (row.ys[j] ?? '').trim() !== '' && Number.isFinite(x) && Number.isFinite(y)) {
      known.push({ x, y })
    }
  }
  known.sort((p, q) => p.x - q.x)
  return known.filter((point, i) => i === 0 || point.x !== known[i - 1].x)
}

/** Fills blank cells in column {@code j} by (log-aware) linear interpolation
 *  between the bracketing known samples; out-of-range rows are left blank. */
function interpolateColumn(rows: FillRow[], j: number, known: { x: number; y: number }[], table: FunctionTableSpec): void {
  for (const row of rows) {
    const x = Number(row.x)
    if (row.x.trim() === '' || !Number.isFinite(x)) continue
    if ((row.ys[j] ?? '').trim() !== '') continue
    if (x < known[0].x || x > known[known.length - 1].x) continue
    const exact = known.find((p) => p.x === x)
    if (exact) { row.ys[j] = String(exact.y); continue }
    let hi = 1
    while (known[hi].x < x) hi++
    const x0 = scaleVal(known[hi - 1].x, table.xLog)
    const x1 = scaleVal(known[hi].x, table.xLog)
    const y0 = scaleVal(known[hi - 1].y, table.yLog)
    const y1 = scaleVal(known[hi].y, table.yLog)
    const t = x1 === x0 ? 0 : (scaleVal(x, table.xLog) - x0) / (x1 - x0)
    row.ys[j] = fmtCell(unscaleVal(y0 + t * (y1 - y0), table.yLog))
  }
}

/** Rows sorted ascending by numeric x (blank x rows sink to the bottom). */
export function sortFunctionRows(table: FunctionTableSpec): FunctionTableSpec {
  const rows = [...table.rows].sort((a, b) => {
    const xa = a.x.trim() === '' ? Number.POSITIVE_INFINITY : Number(a.x)
    const xb = b.x.trim() === '' ? Number.POSITIVE_INFINITY : Number(b.x)
    return (Number.isFinite(xa) ? xa : Number.POSITIVE_INFINITY)
      - (Number.isFinite(xb) ? xb : Number.POSITIVE_INFINITY)
  })
  return { ...detachLegacyFormulas(table), rows }
}

/** Shared 6-significant-figure formatter for table cells. Exported so the
 *  read-only grid formats solver-computed values exactly like the input cells
 *  it renders them alongside. */
export function fmt6(v: number): string {
  return Number.parseFloat(v.toPrecision(6)).toString()
}

/**
 * The string a read-only parametric/ODE grid should paint for one cell.
 *
 * <p>`rows` carries only what was supplied as INPUT, so a code PARAMETRIC table
 * painted from `rows` alone shows its sweep column and nothing else — every
 * solved column stays blank no matter how many runs succeeded. The solved
 * numbers arrive separately in `results` and are merged here.
 *
 * <p>Same rule as `paramComputedValue` in spreadsheet/tableBinding.ts: a
 * computed value shows only where the row solved AND the input was left blank,
 * so the solver's echo of an input never overwrites what the user typed. Lives
 * here, not in the grid component, so it is reachable from a unit test without
 * mounting a canvas — and so the two grids cannot drift apart silently.
 */
export function readOnlyCellText(
  row: ParamRow | undefined,
  outcome: TableRowResult | undefined,
  name: string,
): string {
  const draft = row?.values[name] ?? ''
  if (draft.trim() !== '') return draft
  const computed = outcome?.success ? outcome.values[name] : undefined
  return computed !== undefined && Number.isFinite(computed) ? String(computed) : draft
}

/** Sanitizes free text (axis labels, column headers) into an identifier:
 *  strips `[unit]` suffixes, collapses non-word runs to `_`, and falls back
 *  when the result does not start with a letter. Shared by the digitizer
 *  export and the D10 composition features (sweep→function, CSV→function). */
export function identifier(raw: string, fallback: string): string {
  const cleaned = raw.replace(/\[[^[\]]*\]/g, '').trim().replace(/\W+/g, '_').replace(/^_|_$/g, '')
  return /^[A-Za-z]/.test(cleaned) ? cleaned : fallback
}

/**
 * Builds a Function Table from digitized curves (Story 8.7 "Send to Function
 * Table"): the x grid is the union of every curve's x samples, each curve
 * fills its own rows, and the gaps left by differing samples are
 * interpolated right away via fillMissingCells.
 */
export function functionTableFromDigitizer(input: {
  existing: TableSpec[]
  xName: string
  yName: string
  xLog: boolean
  yLog: boolean
  curves: { param: string; points: { x: number; y: number }[] }[]
}): FunctionTableSpec {
  const count = input.existing.filter((t) => t.kind === 'function').length
  const rows = alignedCurveRows(input.curves.map((curve) => curve.points.map((p) => [p.x, p.y])))
  const is1D = input.curves.length <= 1
  const table: FunctionTableSpec = {
    id: newTableId(),
    kind: 'function',
    name: identifier(input.yName, '').toLowerCase() || `func${count + 1}`,
    argName: identifier(input.xName, 'x'),
    paramName: is1D ? '' : 'param',
    xLog: input.xLog,
    yLog: input.yLog,
    columns: input.curves.map((c) => c.param),
    rows,
    is1D,
  }
  return fillMissingCells(table)
}

/** Align exact numeric X values once per curve. Exact duplicates keep the first sample. */
function alignedCurveRows(curves: number[][][]): CurveRow[] {
  const indexes = curves.map((points) => {
    const byX = new Map<number, number>()
    for (const [x, y] of points) if (!byX.has(x)) byX.set(x, y)
    return byX
  })
  const xs = [...new Set(indexes.flatMap((index) => [...index.keys()]))].sort((a, b) => a - b)
  return xs.map((x) => ({
    x: String(x),
    ys: indexes.map((index) => index.has(x) ? String(index.get(x)) : ''),
  }))
}

/** Builds a read-only Function Table spec from a solver-wire DTO (a TABLE
 * block the backend parsed out of the editor text). The x grid is the union of
 * every curve's x samples; each curve fills its own rows. */
function functionTableFromDto(dto: FunctionTableDto): FunctionTableSpec {
  const is1D = dto.curves.length <= 1 && (dto.curves[0]?.param == null)
  const rows = alignedCurveRows(dto.curves.map((curve) => curve.points))
  return {
    // Stable id keyed by name so the table keeps its identity across solves.
    id: `code-${dto.name.toLowerCase()}`,
    kind: 'function',
    name: dto.name,
    argName: dto.argNames[0] ?? 'x',
    paramName: is1D ? '' : (dto.argNames[1] ?? 'param'),
    xLog: dto.xLog,
    yLog: dto.yLog,
    columns: dto.curves.map((c) => (c.param == null ? '' : String(c.param))),
    rows,
    is1D,
    source: 'code',
    argUnit: dto.argUnits?.[0] ?? undefined,
    paramUnit: dto.argUnits?.[1] ?? undefined,
    outputUnit: dto.outputUnit ?? undefined,
  }
}

/** Builds a read-only Parametric Table spec from a PARAMETRIC ... END block. */
export function paramTableFromDto(dto: ParametricTableDto): ParamTableSpec {
  const rows: ParamRow[] = dto.rows.map((row) => {
    const values: Record<string, string> = {}
    dto.vars.forEach((v, j) => {
      const cell = row[j]
      values[v] = cell == null ? '' : String(cell)
    })
    return { id: crypto.randomUUID(), values }
  })
  return {
    id: `code-param-${dto.name.toLowerCase()}`,
    kind: 'parametric',
    name: dto.name,
    vars: dto.vars,
    rows: rows.length > 0 ? rows : [newParamRow()],
    results: [],
    stats: null,
    checkResult: null,
    checkMessage: '',
    source: 'code',
  }
}

/** Maps a solved ODE Table (from a DYNAMIC block) onto a read-only parametric
 * table: the columns become the table variables and the sampled trajectory the
 * rows, so it renders in the Tables window beside Parametric Tables and is a
 * data source in the Plots window (x = time, y = a state/output) with no extra
 * plot code. The data is solver-populated, so the rows are display-only. */
function odeTableFromDto(dto: OdeTableDto): ParamTableSpec {
  const rows: ParamRow[] = dto.rows.map((row) => {
    const values: Record<string, string> = {}
    dto.vars.forEach((v, j) => {
      const cell = row[j]
      values[v] = cell == null ? '' : String(cell)
    })
    return { id: crypto.randomUUID(), values }
  })
  const columnUnits: Record<string, string> = {}
  dto.vars.forEach((v, j) => {
    const u = dto.units?.[j] ?? ''
    if (u) columnUnits[v] = u
  })
  return {
    id: `code-ode-${dto.name.toLowerCase()}`,
    kind: 'parametric',
    name: dto.name,
    vars: dto.vars,
    rows: rows.length > 0 ? rows : [newParamRow()],
    results: [],
    stats: null,
    checkResult: null,
    checkMessage: '',
    source: 'code',
    origin: 'ode',
    columnUnits,
  }
}

/** Replaces the code-sourced tables in the list with the freshly parsed set
 * from the latest solve/check, leaving GUI tables untouched. */
export function mergeCodeTables(
  existing: TableSpec[],
  functionDtos: FunctionTableDto[] | undefined,
  parametricDtos?: ParametricTableDto[] | undefined,
  odeDtos?: OdeTableDto[] | undefined,
): TableSpec[] {
  const guiTables = existing.filter((t) => t.source !== 'code')
  const codeFunctionTables = (functionDtos ?? []).map(functionTableFromDto)
  const codeParamTables = (parametricDtos ?? []).map(paramTableFromDto)
  const codeOdeTables = odeDtos !== undefined
    ? odeDtos.map(odeTableFromDto)
    : existing.filter((t) => t.source === 'code' && t.kind === 'parametric' && t.origin === 'ode')
  return [...guiTables, ...codeFunctionTables, ...codeParamTables, ...codeOdeTables]
}

/** Makes an independent, editable GUI copy of a code-defined table, decoupled
 * from the editor text. The copy is renamed to avoid clashing with the
 * code-defined original (which still wins in the solver by its text name). */
/** Input-only editable copy: parametric results are not carried over, so
 *  solved outputs cannot become constraints on the next run. */
export function duplicateAsEditable(table: ParamTableSpec, existing?: TableSpec[]): ParamTableSpec
export function duplicateAsEditable(table: FunctionTableSpec, existing?: TableSpec[]): FunctionTableSpec
export function duplicateAsEditable(table: TableSpec, existing?: TableSpec[]): TableSpec
export function duplicateAsEditable(table: TableSpec, existing: TableSpec[] = [table]): TableSpec {
  table = detachLegacyFormulas(table)
  const name = uniqueTableName(`${table.name}_copy`, existing)
  if (table.kind === 'function') {
    return {
      ...table,
      id: newTableId(),
      name,
      rows: table.rows.map((r) => ({ x: r.x, ys: [...r.ys] })),
      columns: [...table.columns],
      source: 'gui',
    }
  }
  return {
    ...table,
    id: newTableId(),
    name,
    rows: table.rows.map((r) => ({ id: crypto.randomUUID(), values: { ...r.values } })),
    results: [],
    stats: null,
    checkResult: null,
    checkMessage: '',
    source: 'gui',
    runStatus: 'not-run',
    resultRevision: undefined,
  }
}

/** Snapshot copy: successful solved outputs are frozen as typed inputs. */
export function duplicateAsSnapshot(table: ParamTableSpec, existing?: TableSpec[]): ParamTableSpec
export function duplicateAsSnapshot(table: FunctionTableSpec, existing?: TableSpec[]): FunctionTableSpec
export function duplicateAsSnapshot(table: TableSpec, existing?: TableSpec[]): TableSpec
export function duplicateAsSnapshot(table: TableSpec, existing: TableSpec[] = [table]): TableSpec {
  if (table.kind !== 'parametric') return duplicateAsEditable(table, existing)
  const name = uniqueTableName(`${table.name}_snapshot`, existing)
  const base = duplicateAsEditable(table, existing)
  return {
    ...base,
    name,
    rows: table.rows.map((row, i) => {
      const values = { ...row.values }
      for (const name of table.vars) {
        if ((values[name] ?? '').trim()) continue
        const v = table.results[i]?.success ? table.results[i].values[name] : undefined
        if (typeof v === 'number' && Number.isFinite(v)) values[name] = String(v)
      }
      return { id: crypto.randomUUID(), values }
    }),
  }
}

const TABLES_KEY = 'frees.tables'

export function loadTables(): TableSpec[] {
  try {
    const raw = localStorage.getItem(TABLES_KEY)
    if (!raw) return []
    return normalizeTables(JSON.parse(raw))
  } catch {
    return []
  }
}

export function saveTables(tables: TableSpec[]) {
  try {
    // Code-sourced tables are re-derived from the editor text on each solve;
    // never persist them (they would otherwise show stale before a re-solve).
    const slim = tables
      .filter((t) => t.source !== 'code')
      .map((t) =>
        t.kind === 'parametric'
          ? { ...t, results: [], stats: null, checkResult: null, checkMessage: '' }
          : t,
      )
    localStorage.setItem(TABLES_KEY, JSON.stringify(slim))
  } catch {
    // storage unavailable: tables still work for the session
  }
}
